export const mockData = [
  {
    id: 1,
    stack: "#1",
    type: "A1",
    days: "52 дня",
    temp: "38.6°C",
    level22: "low",
    level23: "medium",
    level24: "high",
  },
  {
    id: 2,
    stack: "#6",
    type: "B2",
    days: "30 дней",
    temp: "42.1°C",
    level22: "medium",
    level23: "high",
    level24: "high",
  },
  {
    id: 3,
    stack: "#1",
    type: "A1",
    days: "52 дня",
    temp: "38.6°C",
    level22: "low",
    level23: "medium",
    level24: "high",
  },
  {
    id: 4,
    stack: "#6",
    type: "B2",
    days: "30 дней",
    temp: "42.1°C",
    level22: "medium",
    level23: "high",
    level24: "high",
  },
  {
    id: 5,
    stack: "#1",
    type: "A1",
    days: "52 дня",
    temp: "38.6°C",
    level22: "low",
    level23: "medium",
    level24: "high",
  },
  {
    id: 6,
    stack: "#6",
    type: "B2",
    days: "30 дней",
    temp: "42.1°C",
    level22: "medium",
    level23: "high",
    level24: "high",
  },
  {
    id: 7,
    stack: "#1",
    type: "A1",
    days: "52 дня",
    temp: "38.6°C",
    level22: "low",
    level23: "medium",
    level24: "high",
  },
  {
    id: 8,
    stack: "#6",
    type: "B2",
    days: "30 дней",
    temp: "42.1°C",
    level22: "medium",
    level23: "high",
    level24: "high",
  },
  {
    id: 9,
    stack: "#1",
    type: "A1",
    days: "52 дня",
    temp: "38.6°C",
    level22: "low",
    level23: "medium",
    level24: "high",
  },
  {
    id: 10,
    stack: "#6",
    type: "B2",
    days: "30 дней",
    temp: "42.1°C",
    level22: "medium",
    level23: "high",
    level24: "high",
  }
];

const historyMock = [
  { date: "2025-11-10", temperature: 32.1, risk: "low" },
  { date: "2025-11-15", temperature: 35.7, risk: "low" },
  { date: "2025-11-18", temperature: 38.2, risk: "medium" },
  { date: "2025-11-20", temperature: 40.1, risk: "high" },
];

export const mockHistoryPage = {
  stackId: "43",
  coalType: "A1",
  formationDate: "2025-10-01",
  lastTemp: 40.1,
  lastRisk: "high",
  history: historyMock,
};
